from __future__ import annotations

import argparse
import json
import subprocess
import zipfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


IMPORTANT_ARTIFACTS = {
    "compare_aware_result": "samplereverse_compare_aware_result.json",
    "frontier_summary": "samplereverse_compare_aware_frontier_summary.json",
    "strata_summary": "samplereverse_compare_aware_strata_summary.json",
    "guided_pool_result": "samplereverse_compare_aware_guided_pool_result.json",
    "guided_pool_validation": "samplereverse_compare_aware_guided_pool_validation.json",
    "smt_result": "samplereverse_compare_aware_smt_result.json",
    "smt_validation": "samplereverse_compare_aware_smt_validation.json",
    "transform_trace_consistency": "transform_trace_consistency.json",
    "dynamic_compare_path_probe": "dynamic_compare_path_probe.json",
    "profile_transform_hypothesis_matrix": "profile_transform_hypothesis_matrix.json",
    "h1_h3_boundary_validation": "h1_h3_boundary_validation.json",
    "exact2_basin_value_pool_result": "samplereverse_exact2_basin_value_pool_result.json",
    "exact2_basin_value_pool_validation": "samplereverse_exact2_basin_value_pool_validation.json",
    "pairscan_summary": "pairscan_summary.json",
    "bridge_search_result": "bridge_search_result.json",
    "bridge_validation": "bridge_validation.json",
    "checkpoint": "samplereverse_search_checkpoint.json",
    "summary": "summary.json",
    "run_manifest": "run_manifest.json",
}

LATEST_ARTIFACT_KEYS = tuple(IMPORTANT_ARTIFACTS.keys()) + (
    "compare_probe",
    "compare_probe_log",
)

RUNTIME_VALIDATION_KEYS = {
    "guided_pool_validation",
    "h1_h3_boundary_validation",
    "exact2_basin_value_pool_validation",
    "smt_validation",
    "bridge_validation",
    "compare_probe",
    "dynamic_compare_path_probe",
}

STATE_JSON_NAMES = (
    "artifact_index.json",
    "current_state.json",
    "negative_results.json",
    "model_gate.json",
    "task_packet.json",
)
STATE_MARKDOWN_NAMES = (
    "decision_packet.md",
    "codex_execution_report.md",
)
ARCHIVE_STATE_NAMES = (*STATE_JSON_NAMES, *STATE_MARKDOWN_NAMES)
DEFAULT_STATE_DIR = Path("project_state")
DEFAULT_SAMPLE = "samplereverse"
DEFAULT_REPORTS_DIR = Path("solve_reports")
DEFAULT_PROGRESS_LOG = Path("PROJECT_PROGRESS_LOG.txt")
DEFAULT_PACK_NAME = "gpt_context_pack.zip"

DECISION_PACKET_TEMPLATE = """# DECISION_PACKET

## Goal
本轮只做什么。

## Current Evidence
当前证据摘要。

## Do Not Do
禁止重复方向。

## Files To Inspect
Codex 优先审计的文件。

## Required Audit
Codex 执行前必须确认的内容。

## Implementation Scope
允许修改哪些文件。

## Tests
必须运行哪些测试。

## Stop Conditions
遇到什么情况必须停止并报告。
"""

CODEX_EXECUTION_REPORT_TEMPLATE = """# CODEX_EXECUTION_REPORT

## Summary
本轮做了什么。

## Files Changed
修改文件列表。

## Audit Result
审计发现。

## Implementation
实际实现内容。

## Tests
运行的测试命令和结果。

## Generated State Files
生成了哪些 project_state 文件。

## Problems / Uncertainty
仍然不确定的地方。

## Next Suggested Task
下一轮建议。
"""

PROJECT_STATE_README = """# Project State

This directory is the lightweight collaboration interface between web GPT and Codex.

- `task_packet.json`, `current_state.json`, `artifact_index.json`, `negative_results.json`, and `model_gate.json` are compact state files generated by Codex.
- `decision_packet.md` is the handoff written by web GPT.
- `codex_execution_report.md` is the execution report written by Codex.
- `rounds/` stores archived snapshots for prior rounds.

Commit this directory to GitHub. Do not commit `solve_reports/`, local executable samples, `.env`, API keys, or large runtime logs.
"""


def _now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _path_for_json(path: Path) -> str:
    try:
        return str(path.resolve().relative_to(Path.cwd().resolve()))
    except ValueError:
        return str(path)


def _read_json(path: str | Path | None) -> dict[str, Any]:
    if not path:
        return {}
    try:
        raw = Path(path).read_text(encoding="utf-8")
        data = json.loads(raw)
    except (OSError, json.JSONDecodeError):
        return {}
    return data if isinstance(data, dict) else {}


def _write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def _write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.rstrip() + "\n", encoding="utf-8")


def _is_missing_or_default(path: Path, default_content: str) -> bool:
    if not path.exists():
        return True
    try:
        current = path.read_text(encoding="utf-8").strip()
    except OSError:
        return False
    return not current or current == default_content.strip()


def ensure_state_layout(state_dir: Path) -> None:
    state_dir.mkdir(parents=True, exist_ok=True)
    rounds_dir = state_dir / "rounds"
    rounds_dir.mkdir(parents=True, exist_ok=True)
    (rounds_dir / ".gitkeep").touch()
    readme_path = state_dir / "README.md"
    if _is_missing_or_default(readme_path, PROJECT_STATE_README):
        _write_text(readme_path, PROJECT_STATE_README)
    decision_path = state_dir / "decision_packet.md"
    if _is_missing_or_default(decision_path, DECISION_PACKET_TEMPLATE):
        _write_text(decision_path, DECISION_PACKET_TEMPLATE)
    report_path = state_dir / "codex_execution_report.md"
    if _is_missing_or_default(report_path, CODEX_EXECUTION_REPORT_TEMPLATE):
        _write_text(report_path, CODEX_EXECUTION_REPORT_TEMPLATE)


def _safe_mtime(path: Path) -> float:
    try:
        return path.stat().st_mtime
    except OSError:
        return 0.0


def _latest_path(paths: list[Path]) -> Path | None:
    return max(paths, key=_safe_mtime) if paths else None


def _classify_artifact(path: Path, sample: str) -> str | None:
    name = path.name
    lower_name = name.lower()
    if lower_name == "h1_h3_boundary_validation.json" and path.parent.name.lower() == "validation":
        return "h1_h3_boundary_validation_runtime"
    for kind, expected_name in IMPORTANT_ARTIFACTS.items():
        if lower_name == expected_name.lower():
            return kind
    if lower_name.endswith("_compare_probe.json"):
        return "compare_probe"
    if lower_name.endswith("_compare_probe.log"):
        return "compare_probe_log"
    if lower_name.endswith("_search_checkpoint.json") and sample.lower() in lower_name:
        return "checkpoint"
    return None


def _scan_artifact_files(
    reports_dir: Path,
    sample: str,
    harness_run: Path | None = None,
) -> list[Path]:
    candidates: list[Path] = []

    legacy_tool_artifacts = reports_dir / "tool_artifacts"
    if legacy_tool_artifacts.exists():
        candidates.extend(item for item in legacy_tool_artifacts.rglob("*") if item.is_file())

    harness_root = reports_dir / "harness_runs"
    if harness_run is not None:
        run_dirs = [harness_run] if harness_run.exists() and harness_run.is_dir() else []
    elif harness_root.exists():
        run_dirs = [item for item in harness_root.iterdir() if item.is_dir()]
    else:
        run_dirs = []
    if run_dirs:
        for run_dir in run_dirs:
            if not run_dir.is_dir():
                continue
            for direct_name in ("summary.json", "run_manifest.json"):
                path = run_dir / direct_name
                if path.exists():
                    candidates.append(path)
            case_results = run_dir / "case_results"
            if case_results.exists():
                candidates.extend(item for item in case_results.glob("*.json") if item.is_file())
            tool_artifacts = run_dir / "reports" / "tool_artifacts"
            if tool_artifacts.exists():
                candidates.extend(item for item in tool_artifacts.rglob("*") if item.is_file())

    return candidates


def _resolve_latest_run(reports_dir: Path, run_name: str = "") -> Path | None:
    harness_root = reports_dir / "harness_runs"
    if not harness_root.exists():
        return None
    if run_name:
        run_dir = harness_root / run_name
        return run_dir if run_dir.exists() and run_dir.is_dir() else None
    run_dirs = [item for item in harness_root.iterdir() if item.is_dir()]
    return _latest_path(run_dirs)


def build_artifact_index(
    *,
    reports_dir: Path,
    sample: str,
    run_name: str = "",
    max_artifacts: int = 20,
) -> dict[str, Any]:
    generated_at = _now_iso()
    missing: list[str] = []
    if not reports_dir.exists():
        return {
            "sample": sample,
            "reports_dir": _path_for_json(reports_dir),
            "latest_harness_run": None,
            "latest_summary": None,
            "latest_case_results": [],
            "latest_artifacts": {key: None for key in LATEST_ARTIFACT_KEYS},
            "recent_artifacts": [],
            "missing": ["reports_dir"],
            "generated_at": generated_at,
        }

    latest_run = _resolve_latest_run(reports_dir, run_name=run_name)
    latest_summary = latest_run / "summary.json" if latest_run and (latest_run / "summary.json").exists() else None
    latest_case_results = (
        sorted((latest_run / "case_results").glob("*.json"), key=_safe_mtime, reverse=True)
        if latest_run and (latest_run / "case_results").exists()
        else []
    )

    latest_artifact_paths: dict[str, Path] = {}
    recent_artifacts: list[dict[str, Any]] = []
    for path in _scan_artifact_files(reports_dir, sample, harness_run=latest_run if run_name else None):
        kind = _classify_artifact(path, sample)
        if not kind:
            continue
        current = latest_artifact_paths.get(kind)
        if current is None or _safe_mtime(path) > _safe_mtime(current):
            latest_artifact_paths[kind] = path
        recent_artifacts.append(
            {
                "kind": kind,
                "path": _path_for_json(path),
                "size_bytes": path.stat().st_size,
                "modified_at": datetime.fromtimestamp(_safe_mtime(path), tz=timezone.utc)
                .replace(microsecond=0)
                .isoformat()
                .replace("+00:00", "Z"),
            }
        )

    latest_artifacts: dict[str, str | None] = {key: None for key in LATEST_ARTIFACT_KEYS}
    latest_artifacts.update(
        {
            kind: _path_for_json(path)
            for kind, path in sorted(latest_artifact_paths.items())
        }
    )
    if latest_summary and not latest_artifacts.get("summary"):
        latest_artifacts["summary"] = _path_for_json(latest_summary)
    manifest = latest_run / "run_manifest.json" if latest_run else None
    if manifest and manifest.exists() and not latest_artifacts.get("run_manifest"):
        latest_artifacts["run_manifest"] = _path_for_json(manifest)

    if not latest_run:
        missing.append("latest_harness_run")
    if not latest_summary:
        missing.append("summary")
    if not latest_case_results:
        missing.append("case_results")
    for required in ("frontier_summary", "strata_summary"):
        if not latest_artifacts.get(required):
            missing.append(required)
    if not any(latest_artifacts.get(key) for key in RUNTIME_VALIDATION_KEYS):
        missing.append("runtime_validation")

    recent_artifacts.sort(key=lambda item: str(item["modified_at"]), reverse=True)
    return {
        "sample": sample,
        "reports_dir": _path_for_json(reports_dir),
        "latest_harness_run": _path_for_json(latest_run) if latest_run else None,
        "latest_summary": _path_for_json(latest_summary) if latest_summary else None,
        "latest_case_results": [_path_for_json(path) for path in latest_case_results],
        "latest_artifacts": latest_artifacts,
        "recent_artifacts": recent_artifacts[: max(0, max_artifacts)],
        "missing": sorted(set(missing)),
        "generated_at": generated_at,
    }


def _compact_candidate(entry: dict[str, Any] | None) -> dict[str, Any] | None:
    if not isinstance(entry, dict) or not entry:
        return None
    candidate_hex = str(entry.get("candidate_hex") or "").strip()
    cand8_hex = str(entry.get("cand8_hex") or "").strip()
    candidate_prefix = cand8_hex or (candidate_hex[:16] if candidate_hex else "")
    return {
        "candidate_prefix": candidate_prefix or None,
        "candidate_hex": candidate_hex or None,
        "runtime_ci_exact_wchars": entry.get("runtime_ci_exact_wchars"),
        "runtime_ci_distance5": entry.get("runtime_ci_distance5"),
        "compare_semantics_agree": entry.get("compare_semantics_agree"),
        "frontier_role": entry.get("frontier_role"),
        "anchor_mode": entry.get("anchor_mode"),
        "frontier_submode": entry.get("frontier_submode"),
        "source": entry.get("stage") or entry.get("anchor_lineage") or None,
    }


def _best_from_frontier_anchors(
    frontier_summary: dict[str, Any],
    *,
    exact_wchars: int | None = None,
    role_contains: str = "",
) -> dict[str, Any] | None:
    items = frontier_summary.get("frontier_anchor_candidates", [])
    if not isinstance(items, list):
        return None
    filtered: list[dict[str, Any]] = []
    for item in items:
        if not isinstance(item, dict):
            continue
        if exact_wchars is not None and int(item.get("runtime_ci_exact_wchars", -1) or -1) != exact_wchars:
            continue
        if role_contains and role_contains not in str(item.get("frontier_role", "")):
            continue
        filtered.append(item)
    if not filtered:
        return None
    return min(filtered, key=lambda item: int(item.get("runtime_ci_distance5", 1 << 30) or 1 << 30))


def build_current_state(*, artifact_index: dict[str, Any], sample: str) -> dict[str, Any]:
    artifacts = artifact_index.get("latest_artifacts", {})
    artifacts = artifacts if isinstance(artifacts, dict) else {}
    artifact_refs = {key: value for key, value in artifacts.items() if value}
    strata_summary = _read_json(artifact_refs.get("strata_summary"))
    frontier_summary = _read_json(artifact_refs.get("frontier_summary"))
    transform_trace_consistency = _read_json(artifact_refs.get("transform_trace_consistency"))
    dynamic_compare_path_probe = _read_json(artifact_refs.get("dynamic_compare_path_probe"))
    uncertainty: list[str] = []

    exact2 = _compact_candidate(strata_summary.get("best_exact2_runtime"))
    if exact2 is None:
        exact2 = _compact_candidate(_best_from_frontier_anchors(frontier_summary, exact_wchars=2))
    if exact2 is None:
        uncertainty.append("best_exact2_runtime")

    exact1_source = strata_summary.get("best_exact1_runtime")
    if not isinstance(exact1_source, dict) or not exact1_source:
        frontier_candidate = strata_summary.get("best_frontier_runtime")
        if isinstance(frontier_candidate, dict) and int(frontier_candidate.get("runtime_ci_exact_wchars", -1) or -1) == 1:
            exact1_source = frontier_candidate
        else:
            exact1_source = _best_from_frontier_anchors(frontier_summary, exact_wchars=1, role_contains="exact1")
    exact1 = _compact_candidate(exact1_source if isinstance(exact1_source, dict) else None)
    if exact1 is None:
        uncertainty.append("best_exact1_runtime")

    frontier = _compact_candidate(strata_summary.get("best_frontier_runtime"))
    if frontier is None:
        frontier = _compact_candidate(_best_from_frontier_anchors(frontier_summary, role_contains="frontier"))
    if frontier is None:
        uncertainty.append("best_frontier_runtime")

    stage = (
        frontier_summary.get("frontier_stall_stage")
        or strata_summary.get("frontier_stall_stage")
        or frontier_summary.get("frontier_active_lane")
        or None
    )
    reason = (
        frontier_summary.get("frontier_exact1_stall_reason")
        or frontier_summary.get("frontier_converged_reason")
        or strata_summary.get("frontier_exact1_stall_reason")
        or strata_summary.get("frontier_converged_reason")
        or None
    )
    transform_classification = str(transform_trace_consistency.get("classification") or "").strip()
    if transform_classification:
        stage = "transform_consistency"
        reason = transform_classification
    dynamic_classification = str(dynamic_compare_path_probe.get("classification") or "").strip()
    if dynamic_classification:
        stage = "dynamic_compare_path_probe"
        reason = dynamic_classification
    if stage is None:
        uncertainty.append("current_bottleneck.stage")
    if reason is None:
        uncertainty.append("current_bottleneck.reason")

    if artifact_index.get("missing"):
        uncertainty.extend(f"missing:{item}" for item in artifact_index.get("missing", []))

    return {
        "sample": sample,
        "profile": sample if sample == "samplereverse" else None,
        "active_strategy": "CompareAwareSearchStrategy" if sample == "samplereverse" else None,
        "current_mainline": "L15(prefix8)" if sample == "samplereverse" else None,
        "known_transform": (
            ["input", "UTF-16LE", "Base64", "RC4", "compare flag{ prefix"]
            if sample == "samplereverse"
            else []
        ),
        "best_candidates": {
            "exact2": exact2,
            "exact1": exact1,
            "frontier": frontier,
        },
        "current_bottleneck": {
            "stage": stage,
            "reason": reason,
            "confidence": "medium" if stage or reason else "low",
        },
        "latest_transform_trace_consistency": {
            "classification": transform_classification or None,
            "artifact": artifact_refs.get("transform_trace_consistency"),
            "runtime_backed_count": transform_trace_consistency.get("runtime_backed_count"),
            "candidate_count": transform_trace_consistency.get("candidate_count"),
            "stop_reason": transform_trace_consistency.get("stop_reason"),
            "next_bounded_action": (
                transform_trace_consistency.get("decision", {}).get("next_bounded_action")
                if isinstance(transform_trace_consistency.get("decision"), dict)
                else None
            ),
        }
        if transform_trace_consistency
        else {},
        "latest_dynamic_compare_path_probe": {
            "classification": dynamic_classification or None,
            "artifact": artifact_refs.get("dynamic_compare_path_probe"),
            "runtime_backed_count": dynamic_compare_path_probe.get("runtime_backed_count"),
            "candidate_count": dynamic_compare_path_probe.get("candidate_count"),
            "probe_points": dynamic_compare_path_probe.get("probe_points"),
            "next_bounded_action": dynamic_compare_path_probe.get("next_bounded_action"),
        }
        if dynamic_compare_path_probe
        else {},
        "uncertainty": sorted(set(uncertainty)),
        "artifact_refs": artifact_refs,
        "generated_at": _now_iso(),
    }


def build_negative_results(artifact_index: dict[str, Any] | None = None) -> list[dict[str, Any]]:
    results = [
        {
            "direction": "old sample_solver blind search",
            "severity": "soft_block",
            "do_not_repeat": True,
            "reason": "compare-aware profile path is current primary route",
            "override_allowed": True,
            "override_reason_required": True,
        },
        {
            "direction": "only increase guided_pool beam or budget",
            "severity": "soft_block",
            "do_not_repeat": True,
            "reason": "previous project notes indicate low return",
            "override_allowed": True,
            "override_reason_required": True,
        },
        {
            "direction": "use compare_semantics_agree=false candidates as primary frontier",
            "severity": "hard_block",
            "do_not_repeat": True,
            "reason": "runtime/offline semantics disagree",
            "override_allowed": True,
            "override_reason_required": True,
        },
        {
            "direction": "commit full solve_reports directory",
            "severity": "hard_block",
            "do_not_repeat": True,
            "reason": "solve_reports is runtime output and may contain bulky or local data",
            "override_allowed": False,
            "override_reason_required": False,
        },
        {
            "direction": "exact2 basin value-pool evaluation with pools 0:78 1:d5/3e/3c 2:40/7f/80 3:b4/8f 4:9c",
            "severity": "soft_block",
            "do_not_repeat": True,
            "reason": (
                "bounded exact2 value-pool branch generated 18 unique candidates and runtime-validated all 18; "
                "best remained exact2 / distance5 246 with no exact3+ or distance improvement"
            ),
            "override_allowed": True,
            "override_reason_required": True,
        },
        {
            "direction": (
                "H1/H3 fixed 8-candidate prefix8 plus Base64 boundary contrast set: "
                "78d540b49c59077041414141414141, 78d540b49c59076f41414141414141, "
                "78d540b49c59077141414141414141, 78d540b49c5907b041414141414141, "
                "78d540b49c5907d041414141414141, 78d540b49c59077040414141414141, "
                "78d540b49c59077042414141414141, 78d540b49c59076f42414141414141"
            ),
            "severity": "soft_block",
            "do_not_repeat": True,
            "reason": (
                "H1/H3 fixed contrast set was runtime-validated with compare_semantics_agree=true; "
                "best stayed exact2 / distance5 246 and improved_over_exact2=false"
            ),
            "override_allowed": True,
            "override_reason_required": True,
        },
        {
            "direction": "repeat current 5-candidate transform trace consistency audit without new runtime evidence",
            "severity": "soft_block",
            "do_not_repeat": True,
            "reason": (
                "transform trace consistency diagnostic confirmed five runtime-backed candidates agree with "
                "offline UTF-16LE/Base64/RC4/compare trace; next work needs a different bounded evidence source"
            ),
            "override_allowed": True,
            "override_reason_required": True,
        },
    ]
    artifacts = artifact_index.get("latest_artifacts", {}) if isinstance(artifact_index, dict) else {}
    artifacts = artifacts if isinstance(artifacts, dict) else {}
    dynamic_probe = _read_json(artifacts.get("dynamic_compare_path_probe"))
    probe_points = dynamic_probe.get("probe_points", {})
    if isinstance(probe_points, dict) and probe_points.get("pre_rc4_runtime_material") == "unavailable":
        results.append(
            {
                "direction": "focused dynamic compare-path probe with current compare-site hook",
                "severity": "soft_block",
                "do_not_repeat": True,
                "reason": (
                    "dynamic compare-path probe captured compare-site evidence but did not directly expose "
                    "pre-RC4/Base64/RC4 key material; next evidence source should be lower-level instrumentation"
                ),
                "override_allowed": True,
                "override_reason_required": True,
            }
        )
    return results


def _case_results_have_errors(paths: list[str]) -> bool:
    for path in paths:
        data = _read_json(path)
        if str(data.get("status") or "").lower() == "error":
            return True
        if data.get("error"):
            return True
    return False


def _summary_has_errors(path: str | None) -> bool:
    data = _read_json(path)
    try:
        return int(data.get("error_cases", 0) or 0) > 0
    except (TypeError, ValueError):
        return False


def _has_runtime_validation(artifact_refs: dict[str, Any]) -> bool:
    return any(key in artifact_refs for key in RUNTIME_VALIDATION_KEYS)


def _has_disagreeing_candidate(current_state: dict[str, Any]) -> bool:
    best = current_state.get("best_candidates", {})
    if not isinstance(best, dict):
        return False
    for value in best.values():
        if isinstance(value, dict) and value.get("compare_semantics_agree") is False:
            return True
    return False


def build_model_gate(
    *,
    artifact_index: dict[str, Any],
    current_state: dict[str, Any],
) -> dict[str, Any]:
    artifact_refs = current_state.get("artifact_refs", {})
    artifact_refs = artifact_refs if isinstance(artifact_refs, dict) else {}
    missing = list(artifact_index.get("missing", []))
    has_runtime_validation = _has_runtime_validation(artifact_refs)
    bottleneck = current_state.get("current_bottleneck", {})
    bottleneck = bottleneck if isinstance(bottleneck, dict) else {}
    stage = bottleneck.get("stage")
    reason = bottleneck.get("reason")
    case_paths = artifact_index.get("latest_case_results", [])
    case_paths = case_paths if isinstance(case_paths, list) else []

    if "reports_dir" in missing or "latest_harness_run" in missing:
        return {
            "should_call_model": False,
            "context_level": 0,
            "reason": "solve_reports or latest harness run is missing",
            "recommended_packet": "project_state/task_packet.json",
            "next_local_action": "collect_artifacts",
            "missing_evidence": missing,
            "generated_at": _now_iso(),
        }

    if not has_runtime_validation or "frontier_summary" in missing or "strata_summary" in missing:
        needed = sorted(set([*missing, "runtime_validation"] if not has_runtime_validation else missing))
        return {
            "should_call_model": False,
            "context_level": 0,
            "reason": "artifact evidence is incomplete; do not ask the model to guess",
            "recommended_packet": "project_state/task_packet.json",
            "next_local_action": "collect_artifacts",
            "missing_evidence": needed,
            "generated_at": _now_iso(),
        }

    latest_summary = artifact_index.get("latest_summary")
    if _summary_has_errors(str(latest_summary) if latest_summary else None) or _case_results_have_errors(
        [str(item) for item in case_paths]
    ):
        return {
            "should_call_model": False,
            "context_level": 1,
            "reason": "latest harness case has errors",
            "recommended_packet": "project_state/task_packet.json",
            "next_local_action": "inspect_failed_case_result",
            "missing_evidence": [],
            "generated_at": _now_iso(),
        }

    if _has_disagreeing_candidate(current_state):
        return {
            "should_call_model": True,
            "context_level": 2,
            "reason": "offline/runtime compare semantics disagree for at least one current candidate",
            "recommended_packet": "project_state/task_packet.json",
            "next_local_action": "",
            "missing_evidence": [],
            "generated_at": _now_iso(),
        }

    if stage or reason:
        text = f"{stage or ''} {reason or ''}".lower()
        context_level = 3 if "mainline" in text and "wrong" in text else 2
        return {
            "should_call_model": True,
            "context_level": context_level,
            "reason": reason or f"{stage} appears stalled",
            "recommended_packet": "project_state/task_packet.json",
            "next_local_action": "",
            "missing_evidence": [],
            "generated_at": _now_iso(),
        }

    return {
        "should_call_model": False,
        "context_level": 0,
        "reason": "insufficient bottleneck evidence",
        "recommended_packet": "project_state/task_packet.json",
        "next_local_action": "generate_missing_evidence",
        "missing_evidence": ["current_bottleneck"],
        "generated_at": _now_iso(),
    }


def _do_not_do_items(negative_results: list[dict[str, Any]]) -> list[str]:
    items: list[str] = []
    for result in negative_results:
        if not result.get("do_not_repeat"):
            continue
        direction = str(result.get("direction") or "").strip()
        if direction == "old sample_solver blind search":
            items.append("do not return to old sample_solver blind search")
        elif direction == "only increase guided_pool beam or budget":
            items.append("do not only increase beam or budget")
        elif direction == "use compare_semantics_agree=false candidates as primary frontier":
            items.append("do not use compare_semantics_agree=false candidates as primary frontier")
        elif direction == "commit full solve_reports directory":
            items.append("do not commit full solve_reports directory")
        elif direction:
            items.append(f"do not repeat: {direction}")
    items.append("do not scan entire solve_reports unless explicitly needed")
    deduped: list[str] = []
    for item in items:
        if item not in deduped:
            deduped.append(item)
    return deduped


def _task_from_bottleneck(current_state: dict[str, Any]) -> str:
    bottleneck = current_state.get("current_bottleneck", {})
    bottleneck = bottleneck if isinstance(bottleneck, dict) else {}
    best_candidates = current_state.get("best_candidates", {})
    best_candidates = best_candidates if isinstance(best_candidates, dict) else {}
    stage = str(bottleneck.get("stage") or "")
    reason = str(bottleneck.get("reason") or "")
    text = f"{stage} {reason}".lower()
    has_exact1 = isinstance(best_candidates.get("exact1"), dict) and bool(best_candidates.get("exact1"))
    if ("exact1" in text and ("pair" in text or "projected" in text)) or (has_exact1 and "pair" in text):
        return "Generate next decision for exact1 pair_pool bottleneck"
    if stage or reason:
        return f"Investigate stalled {stage or reason} path"
    return "collect_missing_evidence"


def build_task_packet(
    *,
    current_state: dict[str, Any],
    negative_results: list[dict[str, Any]],
    model_gate: dict[str, Any],
) -> dict[str, Any]:
    artifact_refs = current_state.get("artifact_refs", {})
    artifact_refs = artifact_refs if isinstance(artifact_refs, dict) else {}
    best_candidates = current_state.get("best_candidates", {})
    best_candidates = best_candidates if isinstance(best_candidates, dict) else {}
    bottleneck = current_state.get("current_bottleneck", {})
    bottleneck = bottleneck if isinstance(bottleneck, dict) else {}
    has_current_best = any(isinstance(value, dict) and value for value in best_candidates.values())
    has_stall_stage = bool(bottleneck.get("stage") or bottleneck.get("reason"))
    has_runtime_validation = _has_runtime_validation(artifact_refs)
    missing_evidence = model_gate.get("missing_evidence", [])

    if not model_gate.get("should_call_model"):
        return {
            "task": "collect_missing_evidence",
            "sample": current_state.get("sample"),
            "profile": current_state.get("profile"),
            "active_strategy": current_state.get("active_strategy"),
            "current_bottleneck": bottleneck,
            "current_best": best_candidates,
            "do_not_do": _do_not_do_items(negative_results),
            "relevant_files": [
                "reverse_agent/strategies/compare_aware_search.py",
                "tests/test_compare_aware_search_strategy.py",
            ],
            "missing_evidence": missing_evidence,
            "next_local_action": model_gate.get("next_local_action"),
            "reason": model_gate.get("reason"),
            "artifact_refs": artifact_refs,
            "included": ["artifact references", "missing evidence", "model gate reason"],
            "omitted": [
                {
                    "name": "full PROJECT_PROGRESS_LOG.txt",
                    "reason": "too long; use only for strategic review",
                },
                {
                    "name": "full solve_reports",
                    "reason": "runtime output; indexed via artifact_index.json",
                },
            ],
            "sufficiency_check": {
                "has_current_best": has_current_best,
                "has_stall_stage": has_stall_stage,
                "has_negative_results": bool(negative_results),
                "has_artifact_refs": bool(artifact_refs),
                "has_runtime_validation": has_runtime_validation,
            },
            "expected_gpt_output": "project_state/decision_packet.md",
            "generated_at": _now_iso(),
        }

    return {
        "task": _task_from_bottleneck(current_state),
        "sample": current_state.get("sample"),
        "profile": current_state.get("profile"),
        "active_strategy": current_state.get("active_strategy"),
        "current_bottleneck": bottleneck,
        "current_best": best_candidates,
        "do_not_do": _do_not_do_items(negative_results),
        "relevant_files": [
            "reverse_agent/strategies/compare_aware_search.py",
            "tests/test_compare_aware_search_strategy.py",
        ],
        "artifact_refs": artifact_refs,
        "included": [
            "current state",
            "best candidates",
            "stall reason",
            "negative results",
            "artifact references",
        ],
        "omitted": [
            {
                "name": "full PROJECT_PROGRESS_LOG.txt",
                "reason": "too long; use only for strategic review",
            },
            {
                "name": "full solve_reports",
                "reason": "runtime output; indexed via artifact_index.json",
            },
        ],
        "sufficiency_check": {
            "has_current_best": has_current_best,
            "has_stall_stage": has_stall_stage,
            "has_negative_results": bool(negative_results),
            "has_artifact_refs": bool(artifact_refs),
            "has_runtime_validation": has_runtime_validation,
        },
        "model_gate": {
            "should_call_model": model_gate.get("should_call_model"),
            "context_level": model_gate.get("context_level"),
            "reason": model_gate.get("reason"),
        },
        "expected_gpt_output": "project_state/decision_packet.md",
        "generated_at": _now_iso(),
    }


def build_project_state(
    *,
    reports_dir: Path,
    state_dir: Path,
    sample: str,
    run_name: str = "",
    progress_log: Path | None = None,
    max_artifacts: int = 20,
) -> dict[str, Any]:
    _ = progress_log
    ensure_state_layout(state_dir)
    artifact_index = build_artifact_index(
        reports_dir=reports_dir,
        sample=sample,
        run_name=run_name,
        max_artifacts=max_artifacts,
    )
    current_state = build_current_state(artifact_index=artifact_index, sample=sample)
    negative_results = build_negative_results(artifact_index=artifact_index)
    model_gate = build_model_gate(artifact_index=artifact_index, current_state=current_state)
    task_packet = build_task_packet(
        current_state=current_state,
        negative_results=negative_results,
        model_gate=model_gate,
    )

    outputs = {
        "artifact_index": artifact_index,
        "current_state": current_state,
        "negative_results": negative_results,
        "model_gate": model_gate,
        "task_packet": task_packet,
    }
    for name, payload in outputs.items():
        _write_json(state_dir / f"{name}.json", payload)
    return outputs


def new_round(*, state_dir: Path) -> dict[str, Any]:
    ensure_state_layout(state_dir)
    return {
        "state_dir": _path_for_json(state_dir),
        "rounds_dir": _path_for_json(state_dir / "rounds"),
        "initialized": True,
    }


def _resolve_round_dir(state_dir: Path, round_id: str = "") -> Path:
    rounds_dir = state_dir / "rounds"
    rounds_dir.mkdir(parents=True, exist_ok=True)
    if round_id:
        candidate = rounds_dir / round_id
        if candidate.exists():
            raise FileExistsError(f"round already exists: {candidate}")
        return candidate
    index = 1
    while True:
        candidate = rounds_dir / f"round_{index:03d}"
        if not candidate.exists():
            return candidate
        index += 1


def _git_diff_text() -> str:
    try:
        proc = subprocess.run(
            ["git", "diff", "--no-ext-diff"],
            shell=False,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=30,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        return f"git diff unavailable: {exc}\n"
    if proc.returncode != 0:
        return f"git diff failed ({proc.returncode}): {(proc.stderr or proc.stdout).strip()}\n"
    return proc.stdout or ""


def archive_round(
    *,
    state_dir: Path,
    round_id: str = "",
    pytest_result: Path | None = None,
) -> dict[str, Any]:
    ensure_state_layout(state_dir)
    round_dir = _resolve_round_dir(state_dir, round_id=round_id)
    round_dir.mkdir(parents=True, exist_ok=False)
    copied: list[str] = []
    for name in ARCHIVE_STATE_NAMES:
        src = state_dir / name
        dst = round_dir / name
        if src.exists():
            dst.write_bytes(src.read_bytes())
            copied.append(name)
    _write_text(round_dir / "git_diff.patch", _git_diff_text())
    result_src = pytest_result or (state_dir / "pytest_result.txt")
    if result_src.exists():
        (round_dir / "pytest_result.txt").write_bytes(result_src.read_bytes())
    else:
        _write_text(round_dir / "pytest_result.txt", "No pytest_result.txt was available for this round.")
    return {
        "round_id": round_dir.name,
        "round_dir": _path_for_json(round_dir),
        "copied": copied,
    }


def _latest_round_dir(state_dir: Path) -> Path | None:
    rounds_dir = state_dir / "rounds"
    if not rounds_dir.exists():
        return None
    rounds = [path for path in rounds_dir.iterdir() if path.is_dir() and path.name.startswith("round_")]
    return _latest_path(rounds)


def pack_context(*, state_dir: Path, out_path: Path) -> dict[str, Any]:
    ensure_state_layout(state_dir)
    archive_root = "project_state"
    allowed_files: list[tuple[Path, str]] = []
    for name in ARCHIVE_STATE_NAMES:
        path = state_dir / name
        if path.exists():
            allowed_files.append((path, f"{archive_root}/{name}"))
    latest_round = _latest_round_dir(state_dir)
    if latest_round:
        for name in ("pytest_result.txt", "git_diff.patch"):
            path = latest_round / name
            if path.exists():
                allowed_files.append((path, f"{archive_root}/rounds/{latest_round.name}/{name}"))

    out_path.parent.mkdir(parents=True, exist_ok=True) if out_path.parent != Path("") else None
    with zipfile.ZipFile(out_path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for path, arcname in allowed_files:
            archive.write(path, arcname=arcname)
    return {
        "out": _path_for_json(out_path),
        "files": [arcname for _, arcname in allowed_files],
    }


def status_summary(*, state_dir: Path) -> dict[str, Any]:
    artifact_index = _read_json(state_dir / "artifact_index.json")
    model_gate = _read_json(state_dir / "model_gate.json")
    task_packet = _read_json(state_dir / "task_packet.json")
    return {
        "state_dir": _path_for_json(state_dir),
        "latest_harness_run": artifact_index.get("latest_harness_run"),
        "missing": artifact_index.get("missing", []),
        "should_call_model": model_gate.get("should_call_model"),
        "context_level": model_gate.get("context_level"),
        "model_gate_reason": model_gate.get("reason"),
        "task": task_packet.get("task"),
        "expected_gpt_output": task_packet.get("expected_gpt_output", "project_state/decision_packet.md"),
    }


def _print_status(summary: dict[str, Any]) -> None:
    print(f"state_dir: {summary.get('state_dir')}")
    print(f"latest_harness_run: {summary.get('latest_harness_run')}")
    print(f"missing: {summary.get('missing')}")
    print(f"should_call_model: {summary.get('should_call_model')}")
    print(f"context_level: {summary.get('context_level')}")
    print(f"reason: {summary.get('model_gate_reason')}")
    print(f"task: {summary.get('task')}")
    print(f"expected_gpt_output: {summary.get('expected_gpt_output')}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Build low-token project state packets.")
    subparsers = parser.add_subparsers(dest="command", required=True)
    build_parser = subparsers.add_parser("build", help="Build project state JSON files.")
    build_parser.add_argument("--reports-dir", default=str(DEFAULT_REPORTS_DIR))
    build_parser.add_argument("--state-dir", default=str(DEFAULT_STATE_DIR))
    build_parser.add_argument("--sample", default=DEFAULT_SAMPLE)
    build_parser.add_argument("--run-name", default="")
    build_parser.add_argument("--progress-log", default=str(DEFAULT_PROGRESS_LOG))
    build_parser.add_argument("--max-artifacts", type=int, default=20)

    new_round_parser = subparsers.add_parser("new-round", help="Initialize project_state workflow files.")
    new_round_parser.add_argument("--state-dir", default=str(DEFAULT_STATE_DIR))

    archive_parser = subparsers.add_parser("archive-round", help="Archive current project_state files.")
    archive_parser.add_argument("--state-dir", default=str(DEFAULT_STATE_DIR))
    archive_parser.add_argument("--round-id", default="")
    archive_parser.add_argument("--pytest-result", default="")

    pack_parser = subparsers.add_parser("pack", help="Pack compact GPT context files.")
    pack_parser.add_argument("--state-dir", default=str(DEFAULT_STATE_DIR))
    pack_parser.add_argument("--out", default=DEFAULT_PACK_NAME)

    status_parser = subparsers.add_parser("status", help="Print concise project_state status.")
    status_parser.add_argument("--state-dir", default=str(DEFAULT_STATE_DIR))

    args = parser.parse_args(argv)
    if args.command == "build":
        build_project_state(
            reports_dir=Path(args.reports_dir),
            state_dir=Path(args.state_dir),
            sample=str(args.sample),
            run_name=str(args.run_name or ""),
            progress_log=Path(args.progress_log),
            max_artifacts=max(0, int(args.max_artifacts)),
        )
        return 0
    if args.command == "new-round":
        new_round(state_dir=Path(args.state_dir))
        return 0
    if args.command == "archive-round":
        archive_round(
            state_dir=Path(args.state_dir),
            round_id=str(args.round_id or ""),
            pytest_result=Path(args.pytest_result) if args.pytest_result else None,
        )
        return 0
    if args.command == "pack":
        pack_context(state_dir=Path(args.state_dir), out_path=Path(args.out))
        return 0
    if args.command == "status":
        _print_status(status_summary(state_dir=Path(args.state_dir)))
        return 0
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
